name: Windows Workflow

on:
  push:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Create and run Go program
        run: |
          echo 'package main' > hello.go
          echo '' >> hello.go
          echo 'import "fmt"' >> hello.go
          echo '' >> hello.go
          echo 'func main() {' >> hello.go
          echo '    fmt.Println("Hello, Windows from Go!")' >> hello.go
          echo '}' >> hello.go
          
          cat hello.go
          
          # Run the Go program
          go run hello.go
        shell: powershell